global using BuildingBlocks.CQRS;
global using Carter;
global using Catalog.Api.Exceptions;
global using Catalog.Api.Models;
global using FluentValidation;
global using Marten;
global using Marten.Pagination;
global using Marten.Schema;
global using MediatR;
