services:
  catalog.db:
    image: postgres
  
  basket.db:
    image: postgres
  
  order.db:
    image: mcr.microsoft.com/mssql/server
  
  distributed.cache:
    image: redis
    
  catalog.api:
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  ordering.api:
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
      
  basket.api:
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  discount.grpc:
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
      
  message.broker:
    image: rabbitmq:management

volumes:
  catalog_volume:
  basket_volume:
  discount_volume: