services:
  catalog.db:
    image: postgres
  
  basket.db:
    image: postgres
  
  distributed.cache:
    image: redis
  
  catalog.api:
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  basket.api:
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  discount.grpc:
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  catalog_volume:
  basket_volume:
  discount_volume: